### ISSUE TITLE
If a chapter has "show in web" and "show in exports" both checked, then a contributor cannot edit a chapter where he is the author.

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#1103] opened 2018-02-14 15:27 UTC
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
If a chapter has "show in web" **and** "show in exports" both checked, then a contributor cannot edit a chapter where he is the author (owner). If "show in web" or "show in exports" is unchecked a contributor can edit chapters where he is the author (owner).

Is this a wanted behavior? I would expect that as soon as the chapter "becomes visible somewhere" a contributor or author cannot edit his chapters any more. This would mean that this would be correct: As soon as a chapter has "show in web" **or** "show in exports" checked, then a contributor cannot edit a chapter where he is the author (owner) any more.

#### Book Info

Book ID: 16
Book URL: http://localhost/wordpress/pwlo00117r4/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 58.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0

#### WordPress Configuration

Network URL: http://localhost/wordpress/
Network Type: Subdirectory
Version: 4.9.4
Language: en_US
WP_ENV: developer
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 4.5.0
Book Theme: McLuhan
Book Theme Version: 2.0.0-beta.2
Root Theme: Aldine
Root Theme Version: 1.0.0-alpha.6

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Hypothesis: 0.5.0
Pressbooks: 5.0.0-dev

#### Server Configuration

PHP Version: 7.1.12
MySQL Version: 5.6.38
Webserver Info: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.1.12 mod_ssl/2.2.34 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 32M
Post Max Size: 32M
Upload Max Filesize: 32M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.52.1
imagick: Not Installed
xsl: Installed

**Comment by greatislander** [comment] 2018-02-14 17:07
Did the contributor create the chapter in question? If so, they should not have been able to make it visible on web or in exports in the first place

**Comment by greatislander** [comment] 2018-02-14 17:07
(Contributors can't publish.)

**Comment by thomasdumm** [comment] 2018-02-14 17:12
This happens:

1. contributor creates chapter X
2. editor pulishes chapter X by checking  both "show in web" and "show in exports" 
3. contributor cannot edit chapter X 
4. editor unpulishes chapter X by unchecking  either "show in web" or "show in exports" 
5. contributor can edit chapter X

**Comment by thomasdumm** [comment] 2018-02-14 17:15
Question: What means "publish" to you? Does it mean "show in web" and "show in exports" are both checked?

**Comment by greatislander** [comment] 2018-02-15 14:58
This is expected behaviour. In WordPress, contributors can only edit content that is not published because their changes have to be approved by a user with a higher level of permissions. A user (author/editor) with a higher level of permissions can:

- publish content (in the Pressbooks context, make it visible in web and/or exports)
- edit content which is already published

I'm going to close this and if it needs to be revisited in a future release we can re-open it.

**Closed by greatislander** 2018-02-15 14:58 UTC
Labels: question
