### ISSUE TITLE
Auto-generated Hyperlinks in PDF load improperly if they break mid-line

### ISSUE THREAD

**Issue by NMSalmon** [pressbooks/pressbooks#1380] opened 2018-10-02 13:38 UTC
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)? {{_Unsure--(apologies for this)_}}
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

I’ve noticed that while spelled-out hyperlinks in pdf exports are intended to automatically act like hyperlinks and can be clicked to navigate to a browser, if the hyperlink stretches over more than one line–(say, because it’s spelled out in a narrow textbox, as pictured below)–the hyperlink doesn’t function properly. Instead of navigating to the full link, the browser will attempt to load whatever fit just onto that single line.

In the photo below, the mouseover text displays the attenuated link address that the pdf tries to load in the browser. (The link that loads in the browser will stop at “soft-” instead of including the full hyperlink text.)

The text pictured below uses the Jacobs theme and hyphenation is on for the textboxes.
<img width="308" alt="attenuated hyperlinks in pdf export" src="https://user-images.githubusercontent.com/35341860/46351343-b6058880-c61c-11e8-9340-c3720531e1f3.png">
The pictured book is https://wisc.pb.unizin.org/technicalpm/

I've also attached a pdf export example from a different book whose hyperlink behaves in the same way when clicked:
[Pressbooks Prince PDF hyperlink bug.pdf](https://github.com/pressbooks/pressbooks/files/2438088/Pressbooks.Prince.PDF.hyperlink.bug.pdf)

### Steps to Reproduce

1. Export a book with a multi-line web address
2. Click on the link within the pdf document

**Expected behavior:** When the link automatically opens in the browser, the page the browser will open up the complete link listed in the text

**Actual behavior:** The link that the browser attempts to load is only part of the link in the text. The link address that the browser (Chrome, in this case) tries to load cuts off at the page break.

#### Book Info

Book ID: 301
Book URL: https://wisc.pb.unizin.org/technicalpm/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Chrome
Browser Version: 69.0.3497.100
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

#### WordPress Configuration

Network URL: http://wisc.pb.unizin.org/
Network Type: Subdirectory
Version: 4.9.8
Language: en_US
WP_ENV: production
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.5.1
Book Theme: Jacobs
Book Theme Version: 1.1.1
Root Theme: Aldine
Root Theme Version: 1.4.1

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Not Installed
Saxon-HE: Installed

#### Must-Use Plugins

Bedrock Autoloader: 1.0.0
hm-autoloader.php: n/a
network-storage.php: n/a
telemetry.php: n/a
Unizin Allow Custom Post Types: 1.0
Unizin Allow Plugins: 1.0.0
Unizin Allow Upload Extensions: 1.0.0
Unizin Mail From: 1.0.0
UW-Madison Kaltura Enable oEmbed: 1.0

#### Network Active Plugins

CM Tooltip Glossary: 3.6.4
H5P: 1.10.3
H5P xAPI: 0.1.7
Hypothesis: 0.5.0
iframe: 4.3
LTI: 0.1
Pressbooks: 5.5.1
Pressbooks BISAC: 2.0.0
Pressbooks Stats: 1.5.0
Pressbooks Whitelabel: 1.3.0
Redis Object Cache: 1.3.8
Regenerate Thumbnails: 3.0.2
TablePress: 1.9.1
TablePress Extension: DataTables Buttons: 1.1
Thin CC Exporter: 0.1.1
User Activation Keys: 4.6
Wisc Content Auth LTI: 0.2.7
Wisc H5P LTI Outcomes: 0.2.8
WP QuickLaTeX: 3.8.5

#### Book Active Plugins

CM Tooltip Glossary: 3.6.4
H5P: 1.10.3
H5P xAPI: 0.1.7
Hypothesis: 0.5.0
iframe: 4.3
LTI: 0.1
Pressbooks: 5.5.1
Pressbooks BISAC: 2.0.0
Pressbooks Stats: 1.5.0
Pressbooks Whitelabel: 1.3.0
Redis Object Cache: 1.3.8
Regenerate Thumbnails: 3.0.2
TablePress: 1.9.1
TablePress Extension: DataTables Buttons: 1.1
Thin CC Exporter: 0.1.1
User Activation Keys: 4.6
Wisc Content Auth LTI: 0.2.7
Wisc H5P LTI Outcomes: 0.2.8
WP QuickLaTeX: 3.8.5

#### Inactive Plugins

Akismet Anti-Spam: 4.0.8
Parsedown Party: 1.1.1

#### Server Configuration

PHP Version: 7.1.17-1+ubuntu16.04.1+deb.sury.org+1
MySQL Version: 5.6.10
Webserver Info: nginx/1.13.12

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 50M
Post Max Size: 50M
Upload Max Filesize: 50M
Time Limit: 300
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.47.0
imagick: Not Installed
xsl: Installed

**Comment by greatislander** [comment] 2018-12-20 15:39
Hi @NMSalmon, we've tested extensively and cannot reproduce. I'm going to close this for now. Please feel free to reopen with more details if you can provide them. Thanks!

**Closed by greatislander** 2018-12-20 15:39 UTC
Labels: bug
