### ISSUE TITLE
Some localized strings don't update until book info is saved a second time

### ISSUE THREAD

**Issue by techfiz** [pressbooks/pressbooks#2359] opened 2021-09-06 12:24 UTC
### Description

When a book has more than one 'author' assigned via book info, the authors' names are displayed on the book home page with the word 'and' between the second to last and last authors' names. When a new language is set in book info, this string isn't updated until book info is saved twice. Appears to be a caching issue.

### Steps to Reproduce

1. Add two author or more authors to a book via book info. 
2. View the book home page and observe that the word 'and' has been inserted between the authors' names
3. Change the book language in book info to a language other than English (like French, or Spanish)
4. View the book home page and observe that the word 'and' has not been localized as expected (_et_ or _y_)
5. Save book info a second time
6. Observe that the word has been localized
7. Change book language back to English
8. Observe that the string has not been changed to English
9. Save book info a second time
10. Observer that the word has changed back to English

**Expected behavior:** 
The word 'and' between authors' names should be localized like other metadata on the book home page upon save of book info

**Actual behavior:** 
The word 'and' remains in English until book info has been saved a second time.

**Comment by techfiz** [comment] 2021-09-10 16:27
@SteelWagstaff Add two authors to get and between the author names on title page. This "and" between names appear in english and there is no option to change that to respective script like chapter and part in admin.

**Comment by SteelWagstaff** [comment] 2021-09-10 18:02
We generate the book author text here: https://github.com/pressbooks/pressbooks-book/blob/8013a8c5672f4a5673fba26d40b55cc797d00ba9/partials/content-cover-book-header.php#L17

**Comment by SteelWagstaff** [comment] 2021-09-15 15:01
@techfiz can you help us investigate this by telling us what language you're trying to use for your target book, providing the URL for a sample book where you're experiencing the error? We'd also love to see the contents of the 'diagnostics' page from your network, as well as a list of any 'site languages' that you've installed on your server. This will help us reproduce your issue and fix it more quickly.

**Comment by SteelWagstaff** [comment] 2021-09-22 14:33
Notes: The language does appear to be updated to use the localized string, but with a delay or lag. If a book is in English and I change the language to French, nothing happens to the author string. If I then change to Spanish, the 'and' in the author string appears in French. If I then change to Arabic, the 'and' appears in Spanish, and so forth. Not sure why this is happening, but it is a bug and should be fixed in a future release.

**Comment by richard015ar** [comment] 2021-09-23 15:38
Seems to be a cache problem. If we save again in the Book Info section the cache is refreshed and the `and` is translated properly.
See https://github.com/pressbooks/pressbooks/blob/f57ed1cf5c5bd98a8174b019f40f323ee6269e28/inc/class-book.php#L83 to see which information we read from cache.

**Comment by SteelWagstaff** [comment] 2021-09-23 17:23
@techfiz we'll be investigating and trying to fix this bug in a future release of Pressbooks. For now, you should be able to have this word localized if you change the language in book info, click 'Save' in the Save Book Information section, and then click 'Save' a second time. The second save should cause the language selection to 'catch up' with your choice for the string that displays authors names. Hope this workaround helps while we fix the underlying issue.

**Comment by techfiz** [comment] 2021-09-23 19:02
tried to setup a sample book here https://linuxaayana.pressbooks.com/ -
Take a look at the metadata here with "and"  in english while the language set for the book is Kannada. 

<img width="611" alt="authors" src="https://user-images.githubusercontent.com/7073833/134567660-a1bd7479-1af2-4e7c-a501-1e95198cb9c3.png">

Here is the admin section where we localize the "Part" and "Chapter" to respective words in our language. 
 
<img width="1344" alt="admin-section" src="https://user-images.githubusercontent.com/7073833/134567705-4ec51142-fddf-4857-b43f-12725b97803c.png">

Note: This issue can be extended to the word "Contents" in the index page. As of now there is no way we can localize that to Kannada and make it apppear as "ಪರಿವಿಡಿ" 

Hope this helps.

**Comment by techfiz** [comment] 2021-09-24 04:09
@SteelWagstaff @richard015ar I realize this has to come from the language po file. 

I have started looking at the transifex strings (Kannada i had requested to be added but translation work was not started. I shall contribute here)

The word - and is found here and I have now translated that on transifex. 
------
Occurrences
inc/modules/export/namespace.php:89, inc/modules/themeoptions/class-globaloptions.php:389, inc/utility/namespace.php:1292, inc/utility/namespace.php:1297, inc/utility/namespace.php:1317, inc/utility/namespace.php:1323, templates/admin/covergenerator.php:53
Context
None
Resource
pressbooks.pot
------

I shall try adding the language files in my installation and confirm that it works as expected.

**Comment by omshivaprakash** [comment] 2021-11-07 17:54
@SteelWagstaff I have made contributions to Kannada (kn) on transfix. is it possible to import them here? That would make it easier to resolve the issues related to this bug?

**Comment by SteelWagstaff** [comment] 2022-01-06 05:56
@omshivaprakash Kannada translations have been added to recent releases of Pressbooks. If you update to the latest version and update your cache, are you still seeing this issue or has it been resolved?

**Comment by omshivaprakash** [comment] 2022-01-09 17:23
@SteelWagstaff This is still not resolved. This issue remains unresolved. Tried with multiple authors for both under book information and also for individual chapters - in both places I see AND (in caps for book authors) and 'and' in small letters in Index page, chapter title and in chapter header as well.

**Comment by richard015ar** [comment] 2022-11-22 18:30
I disabled the cache on integrations. Although it still happens with the cache disabled, I can confirm it is not a cache problem.
Nevertheless, I am not able to replicate it locally. 
More updates to come.

**Comment by richard015ar** [comment] 2022-11-22 19:34
I can be replicated on integrations, nevertheless just like local env, it works as expected on integrations2

**Comment by richard015ar** [comment] 2022-11-22 21:20
I activate precisely the same plugins and themes on integrations and integrations2. Both have identical versions of plugins and themes and share the same vendor folder.
Integrations2 works; integrations fail.
More to come tomorrow.

**Comment by richard015ar** [comment] 2022-11-23 17:35
Moving this to In Progress to confirm the following actions with Steel.

**Comment by SteelWagstaff** [comment] 2022-11-28 22:15
It appears that the word and is localized in pressbooks/pressbooks: https://github.com/pressbooks/pressbooks/blob/56be4dffcb09a83dc27cbcfece7d0969d3cf9228/inc/utility/namespace.php#L1321-L1326 while most/all of the other text on the webbook home page is localized in pressbooks-book. I think the issue here is that content that is localized in pressbooks/pressbooks is controlled by the user's profile language, while content in the book itself is localized by the book language set in book info. One possible solution is to add the `and` string to the pressbook-book localization file and reference it in pressbooks/pressbooks?

**Comment by richard015ar** [comment] 2022-11-29 12:24
Update: I was researching how to add a translation for a new string on pressbooks-book, but it looks like there's a part of the process I'm probably missing. I sent an email to Ned to guide me on the process. As a result of his help, I will write some documentation for others devs.

**Comment by SteelWagstaff** [comment] 2022-11-29 19:39
@techfiz here's what we think is happening. Pressbooks includes localized translations for several strings, including the copyright license and the word 'and' which appears between authors names on the book home page. The McLuhan theme includes other localized translations. By default, we will use the localized translations for the McLuhan strings on the webbook homepage based on the language set for a book in book info. 
![Screenshot from 2022-11-29 11-38-02](https://user-images.githubusercontent.com/13485451/204631398-2547ee13-7341-4be0-a4e5-1f05e4cd985e.png)

However, users also have the ability to set their profile language preferences. 
![Screenshot from 2022-11-29 11-36-46](https://user-images.githubusercontent.com/13485451/204631576-86128e8a-5eb9-4ee9-92b9-482f9ad07f92.png)

If a user chooses to override the site default, then the strings which are localized in pressbooks/pressbooks will use the translations for this language. The word `and` between the authors names appears to be one of these strings.

**Comment by omshivaprakash** [comment] 2022-11-30 19:43
@SteelWagstaff and team. Thank you for the updates. I found that the solution shared works for web.
<img width="282" alt="Screenshot 2022-12-01 at 1 12 37 AM" src="https://user-images.githubusercontent.com/115216/204893151-4dfdcfc4-51a0-4a2b-bc96-95140d08dc7c.png">

But, I see that the issue persists on PDF export. 
Title page image given below:

<img width="541" alt="Screenshot 2022-12-01 at 1 13 08 AM" src="https://user-images.githubusercontent.com/115216/204893229-b73ff43e-ff70-43f2-a2bc-5a79c5755edf.png">

Also the copyright page:

<img width="448" alt="Screenshot 2022-12-01 at 1 13 33 AM" src="https://user-images.githubusercontent.com/115216/204893304-9172477e-3f7a-414c-8cfe-9ec1d79b8c9b.png">

**Comment by SteelWagstaff** [comment] 2022-12-05 17:57
@richard015ar We can improve this by making a stub file with an array of translatable strings in pressbooks-book. See https://github.com/accessibility-exchange/platform/blob/dev/app/strings.php for an example. Then, we should change the localization domain in pressbooks/pressbooks to reference pressbooks-book for any strings that should use book info localization along with an inline comment explaining why we’re referencing the pressbooks-book domain so future devs don't revert this back. For the exports – we should always set locale to book info locale (when generating XHTML for example) -- probably can be done by using pressbooks-book domain in places like this: https://github.com/pressbooks/pressbooks/blob/b5bd967339fddd6f51d7a417e4f26b7bc58588dc/inc/modules/export/xhtml/class-xhtml11.php#L1074-L1101

**Closed** 2022-12-08 17:27 UTC
Labels: bug, cool down
