### ISSUE TITLE
Embed video links in PDF exports fallback links redirects to network home page

### ISSUE THREAD

**Issue by jocelynpb2** [pressbooks/pressbooks#3007] opened 2022-11-07 16:09 UTC
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Embed video links are not directing to videos on the PDF and Digital PDF exports in several tested themes (Adunis, Atwood 2, Anderseen, Asimov, and Malala). Instead, the fallback links are directing to the network home page in these tested themes. H5P element fallback links seem to be working properly in these tested themes.

Tested Lewis and embed video links are working.

### Steps to Reproduce

1. Insert embed video link anywhere in the book (front matter, main body, or back matter)
2. Theme Options --> PDF Options --> all default settings (6x9, Indent paragraphs, etc.)
3. Themes --> Adunis (or any other listed tested theme)
4. Export book (PDF or Digital PDF) and open book

**Expected behavior:** Click on embed video link on PDF export (where fallback link is generated on PDF), be directed to youtube video
<img width="280" alt="image" src="https://user-images.githubusercontent.com/113727966/200607022-5f1302ff-82b7-4c7c-b04f-f7f483c63721.png">
Clickable link (Malala), expecting to direct to youtube video 

**Actual behavior:** Click on embed video link, directed to network home page

A closely related issue, [that was reported by a network manager](https://pressbooks.zendesk.com/agent/tickets/13213), is that in the PDF export using the Malala theme, embed video fallback links are unclickable. When these links are copy+pasted into the browser, they are missing a slash after https:/ and have a space in them. 

<img width="280" alt="image" src="https://user-images.githubusercontent.com/113727966/200603003-738edfc4-09b8-4590-9408-521d3da825e2.png">
Unclickable link in PDF export

**Comment by SteelWagstaff** [comment] 2022-11-09 15:45
Closing as duplicate of https://github.com/pressbooks/pressbooks/issues/2512

**Closed by SteelWagstaff** 2022-11-09 15:45 UTC
Labels: bug
