### ISSUE TITLE
Improve top-level navigation for all Pressbooks users

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#3152] opened 2023-01-28 18:53 UTC
As a network manager, I want to clearly see and understand the various high-level administrative options I have from my top-level navigation menu (administer network, my books, create a book, clone a book, add users, edit my profile).

As a regular end user of Pressbooks, I want to be able to see a list of all the books I have accounts in and key actions I can take (create a book, clone a book, edit my profile)

To that end, we should simplify and improve the top-level navigation menu to make it easier for users to find and perform the actions they want to do.

## Design notes 
See https://www.figma.com/file/CU0d5QeDcCRK9LK2xUuYQp/Network-Manager-Dashboard?node-id=640%3A503&t=m955UZbuNqroGbCK-0 and https://docs.google.com/document/d/1227gW5CmccJNUhxfTduViB3kkKpzJKd_UdWP49oE5pk/edit

Key features:
- [x]  remove PB logo menu for all users
- [x]  Combine the two admin menus visible for super admins & network managers into a single menu called 'Administer Network'
- [x]  Display a my books menu for all users. Clicking on it opens new user dashboard. If they have no books, that's all it does. If they have books, display books in list like we do now. Clicking on a book opens book dashboard like it does now.
- [x]  Add new 'create a book' and 'clone a book' buttons for all users with permissions to do this
- [x]  Add new 'add users' button for network managers. Clicking this button should take them to a new 'bulk add user' page at network level that is a simplified version of our current bulk add user page at the book level. Let's them enter email addresses to add many users as 'lowly users' all at once.
- [x]  Change appearance of the 'profile' link in top right

**Comment by SteelWagstaff** [comment] 2023-02-20 23:00
I pushed several CSS changes to the WiP branch. I think this could still use a bit of clean up and consolidation, but it's getting closer to my desired appearance.

**Comment by SteelWagstaff** [comment] 2023-02-23 22:53
This has been deployed to dev environments and is ready for testing/review by @tw77 and @MichelleWeremczuk.

**Comment by tw77** [comment] 2023-02-27 16:56
As a regular user who hasn't created any books yet, 'My Books' in the top nav links to the user dashboard:

<img width="1214" alt="Screenshot 2023-02-27 at 8 53 47 AM" src="https://user-images.githubusercontent.com/44182629/221628224-c84fcd81-37c0-4856-8c85-7db2e433b60f.png">

As a regular user who _has_ created a book, 'My Books' in the top nav links me back to the book dashboard for the one book I've created. I can no longer reach the user dashboard. Clicking 'My Books' or clicking **Dashboard > Home** in the left sidebar both keep me on the same page:

https://user-images.githubusercontent.com/44182629/221628529-5e11305c-8c36-4be2-8502-329333c3362b.mp4

**Comment by tw77** [comment] 2023-02-27 17:40
Just a thought, but if the "Add Users" button in the new top nav were to have a drop-down with "Add New" and "Bulk Add" options, this might help solve the potential confusion that I noted when testing the new side nav here: https://github.com/pressbooks/pressbooks-network-analytics/issues/284#issuecomment-1446745079.

As I note there, making Bulk Add the sole option eliminates the ability to assign custom usernames when adding new users to the network, since it always draws the username from the email address.

**update**: addressed by Steel in comments in the linked issue.

**Comment by tw77** [comment] 2023-02-27 19:35
Tested and the issue filed above in pressbooks/pressbooks is the only one I've found, everything else works well.

**Comment by MichelleWeremczuk** [comment] 2023-02-27 20:52
With the PB logo being removed and the global nav options shifted left, the dropdown menu now obscures the side nav options. I would keep the space that the PB logo had occupied as a solid red/empty block to keep it a bit cleaner. I also understand that these options are duplicated across both the side nav and menu dropdown, and so the dropdown feels a bit redundant (although it makes sense to have it available to access when you are on the user or book dash). 


![Screenshot 2023-02-27 at 1 21 47 PM](https://user-images.githubusercontent.com/107423387/221679577-18682bda-cf98-4f02-a18e-09141c5e5593.png)

Icons are in progress, but I still wanted to flag this. On hover, the right profile avatar has a white square behind it. It would be better if the icon could invert colours, or have a stroke on hover to keep it within the circle.

<img width="341" alt="Screenshot 2023-02-27 at 1 15 32 PM" src="https://user-images.githubusercontent.com/107423387/221681519-f84c43ed-ff94-41c9-9cb0-b8bcc9b607eb.png">

The items on the right hand side of the global nav can be nudged to the left to give some breathing room to the profile icon. The right margin should be about 1.5 of the current spacing between these elements.

![Screenshot 2023-02-27 at 1 42 49 PM](https://user-images.githubusercontent.com/107423387/221681435-28be4e34-c40f-490c-9272-282d57a46d19.png)

In support resources, network manager guide illustration can be made a bit smaller. The other three illustrations are a good size.

**Comment by SteelWagstaff** [comment] 2023-02-27 22:27
Proposals:
- [x] Add the PB icon back to top nav -- no children, links directly to pressbooks.com
- [x] Change the hover state for profile icon to be 2px solid white and give it a 50% border radius
- [x] Increase padding-right on the profile icon to 15px

**Comment by SteelWagstaff** [comment] 2023-02-28 01:35
Opened a PR (https://github.com/pressbooks/pressbooks/pull/3209) to do all three things described in previous comment and assigned to Dalcin for review.

**Comment by tw77** [comment] 2023-03-02 16:40
Tested and confirmed that PB logo appears in top nav bar for all logged in users and links to pressbooks.com. Screen reader text reads 'About Pressbooks' 

Profile avatar receives thin white border on hover and active states, and has more right padding.

FYI, that thin white border around the profile avatar differs for regular users vs. super admin / network managers. Here are screenshots of both with the same level of zoom. The shape around the avatar in the first screenshot is more circular:

**As super admin / network manager:**
<img width="1440" alt="Screenshot 2023-03-02 at 8 36 06 AM" src="https://user-images.githubusercontent.com/44182629/222492980-8ca27852-d747-476b-b236-375310c022cc.png">

**As regular user:**
<img width="1440" alt="Screenshot 2023-03-02 at 8 36 34 AM" src="https://user-images.githubusercontent.com/44182629/222493139-983bb219-7ae0-4d38-86d6-2608ba83e402.png">

**Comment by tw77** [comment] 2023-03-02 20:44
Regular users see the expected circular border around the avatar when they're on the book dashboard, where those warning messages aren't shown. Those messages are only shown to users on the user dashboard on dev networks. This discrepancy with the border shouldn't occur on staging or production environments.

**Closed as completed by tw77** 2023-03-02 20:44 UTC
Labels: UX / UI
