### ISSUE TITLE
QuickLaTeX basic settings don't apply to export formats

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1818] opened 2019-10-30 19:52 UTC
### Description

Users can control basic settings about the display of their QuickLaTeX equations by going to **Settings > QuickLaTeX > Basic Settings**. This includes the ability to set: 

- font size
- font color
- equation alignment
- equation number position
- background color 

These settings only apply to the webbook format. Below is an example of a book when the equation alignment setting is on "Center". 

Webbook: 
![Screen Shot 2019-10-30 at 3 48 12 PM](https://user-images.githubusercontent.com/39064028/67893289-afea2000-fb2c-11e9-9167-26d9a25ef633.png)

PDF: 
![Screen Shot 2019-10-30 at 3 48 32 PM](https://user-images.githubusercontent.com/39064028/67893309-baa4b500-fb2c-11e9-8c3d-985fdb80da83.png)

Example: https://equationalignment.textopress.com/

### Steps to Reproduce

1. Activate QuickLaTeX from the plugins menu
2. Copy in some sample QuickLaTeX, including a standalone equation, then save the chapter. 
3. Go to **Settings > QuickLaTeX > Basic Settings** and adjust some of the defaults, then save
4. View in webbook and export to ebook and PDF formats 

**Expected behavior:** QuickLaTeX settings apply to all supported formats, or the interface reflects that limitation. 

**Actual behavior:** QuickLaTeX settings only apply to the webbook format.

**Comment by SteelWagstaff** [comment] 2021-06-06 05:12
Closing as duplicate of #1865

**Closed by SteelWagstaff** 2021-06-06 05:12 UTC
Labels: bug, export formats, third party
