### ISSUE TITLE
Investigate @context value for JSON-LD metadata

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1749] opened 2019-08-14 17:36 UTC
Google Search Console has sent out warnings indicating that "Unparsable structured data issues detected" on our books. Specifically, Search Console suggests that the current `@context` value of `"http:\/\/bib.schema.org"` is unparsable. Per testing of https://book.pressbooks.com/chapter/book-and-the-internet-hugh-mcguire using https://search.google.com/structured-data/testing-tool/u/0/ it appears that replacing this value with either `"http:\/\/schema.org"` or `"https:\/\/schema.org"` would resolve the error. If fix is warranted, locations where this occurs can be found here: https://github.com/pressbooks/pressbooks/search?q=bib.schema.org&unscoped_q=bib.schema.org

**Comment by greatislander** [comment] 2019-08-14 20:29
It appears that the bibliographic extension has been merged into top-level Schema.org. For example: https://bib.schema.org/Chapter now redirects here: https://schema.org/Chapter

**Comment by greatislander** [comment] 2019-08-14 20:32
To validate, try testing with: https://search.google.com/structured-data/testing-tool/

**Comment by SteelWagstaff** [comment] 2019-08-14 20:35
Thanks Ned. I tested the sample link in original ticket there and found the error was resolved when I replaced bib.schema.org with schema.org, which confirmed this hunch. We'll do a bit more investigating, but this is helpful.

**Comment by philbarker** [comment] 2019-08-15 09:13
Here's the documentation for the change in how schema.org handles hosted extensions such as bib.schema was: https://schema.org/docs/extension.html 

In short, it confirms that they now all have URIs that start with http://schema.org/  (even the remaining extension, pending, will work with that URI/context)

**Closed** 2019-08-16 14:00 UTC
Labels: X-Small - 1

**Comment by Beyond-Enough** [comment] 2023-07-14 08:57
Hello Everyone.
Now the testing link: https://search.google.com/structured-data/testing-tool/ 
has started giving unparsable error even on @context value of "http:\/\/schema.org"

Please help.

**Comment by philbarker** [comment] 2023-07-14 09:35
hmm, try https://schema.org/

The `s` shouldn't matter, but might? The trailing / will matter if you left it out.  

Or it might be a Google thing. Google doesn't accept all valid schema.org and has it's not always clear that the problem is with Google not recognizing something that is valid or an error in the markup. Knowing the exact error message and what was being tested might help figure that out.

**Comment by Beyond-Enough** [comment] 2023-07-14 09:54
Thank you for reply. 
We already have tried multiple such combinations like http with 's' as well as without 's'. Keeping '/' at the end, as well as without '/'. It kept giving the same error.

The code shows zero error on: https://validator.schema.org/
however shows unparsable error on: https://search.google.com/structured-data/testing-tool/ (highlights in red the code: "@context":"http://schema.org",

Exact Error: 
![image](https://github.com/pressbooks/pressbooks/assets/139544135/30ad4120-a0a5-4fd8-a899-2ce550dba57c)

**Comment by philbarker** [comment] 2023-07-14 10:18
Sorry, I can't reproduce that result from a screenshot. 

The fact that it works on  https://validator.schema.org/ suggests that the schema.org side of it is  fine. 

Certainly the line `"@context": "http://schema.org/",` is fine.

Are you using PressBooks? If not then this is the wrong place to try to find a solution.  Even if you are, try the Google search forums, there will be people there who know about the Google testing tool.

**Comment by Beyond-Enough** [comment] 2023-07-14 10:30
Thank you so much for your guidance.
Sharing the code, to reproduce the error.
Have already tried other forums for help in vain.

**Comment by philbarker** [comment] 2023-07-14 10:48
Sorry, I doubt anyone here can help.

With the trailing slash (` "@context":"http://schema.org/",`),  that code validates 
- here: https://search.google.com/test/rich-results/result?id=QCgjSxSu9dV1AOSS5aCZlg
- here: https://json-ld.org/playground/
- here: https://validator.schema.org/

**Comment by Beyond-Enough** [comment] 2023-07-14 12:06
Thank you for the entire support @philbarker 
We identified the error. When we removed the Spaces in our entire code, the tool stopped giving the error.

Thank you so much again.
