### ISSUE TITLE
Include custom features (CSS, formatting) into Cloning process

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/pressbooks#2188] opened 2020-12-03 22:54 UTC
### Feature Description

Cloning only really brings over core content - metadata, H5P, glossary, images, content; everything that composes the core HTML content. It does not factor for themes, inline HTML (i.e. table formatting) and custom CSS.

We have received many suggestions to have custom adjustments included in the cloning process to have an exact copy of a cloned book.

### Feature Use Case

This would generally broaden the capabilities of cloning. All cloning processes could potentially be affected by/benefit from this feature.

### Other Notes

It would be worthwhile to have a multiselect/checkbox options to select which custom components to clone.

**Comment by SteelWagstaff** [comment] 2021-06-06 04:30
Closing as duplicate of #1284

**Closed by SteelWagstaff** 2021-06-06 04:30 UTC
Labels: API & cloning, book theme options
