### ISSUE TITLE
Copyright year not included in exports when copyright license other than default / All Rights Reserved is specified

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks#3249] opened 2023-03-15 16:18 UTC
https://github.com/pressbooks/pressbooks/blob/5a20ea04f2e103ca381733a03c7b67f3da9b789c/inc/modules/export/class-export.php#L449

https://github.com/pressbooks/pressbooks/blob/d10da5d2679fbe57ad6da703e3ef68db8a3b5a0e/inc/class-licensing.php#L287

A fix for this would be to always print the copyright year regardless of which license is selected.

**Comment by SteelWagstaff** [comment] 2023-03-22 17:16
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pressbooks-Product-Backlog-60ae7d807f6e370010b3d5be/issues/pressbooks/pressbooks/3249?planning-poker) with Zenhub @arzola @fdalcin

**Comment by SteelWagstaff** [comment] 2023-05-10 19:34
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pressbooks-Product-Backlog-60ae7d807f6e370010b3d5be/issues/pressbooks/pressbooks/3249?planning-poker) with Zenhub @richard015ar

**Comment by greatislander** [comment] 2023-07-18 23:53
To clarify, what would be the appropriate format for each of these? Currently the `getLicense` method returns the following:

### Creative Commons

"_Title_ by Author Name is licensed under a Creative Commons Attribution License, except where otherwise noted."

### All Rights Reserved

"_Title_ Copyright &copy;2023 by Author Name. All Rights Reserved."

### Public Domain

"This work (_Title_ by Author Name) is free of known copyright restrictions."

### Creative Commons Zero

"To the extent possible under law, Author Name has waived all copyright and related or neighboring rights to _Title_, except where otherwise noted."

I'm not sure where the year should be inserted into each of these strings and it seems like some editorial input may be needed before I proceed with implementing this change, @SteelWagstaff.

**Comment by greatislander** [comment] 2023-07-19 00:00
One further note— the beta Creative Commons chooser does include a copyright year in the generated string: https://chooser-beta.creativecommons.org/

However the presence of a copyright symbol in a Creative Commons license is surprising (at least to me, and likely to others).

**Comment by SteelWagstaff** [comment] 2023-07-20 15:33
Yes, this can be a little confusing. CC licensed works are copyrighted, because that’s the default legal position of works once they received fixed form. However, rather than being ‘all rights reserved’, the copyright holders preemptively grant the public certain permissions, provided they comply with the conditions of the license. As I understand it, the only exception is CC0, where rights holders attempt to renounce copyright before it technically expires: https://creativecommons.org/share-your-work/public-domain/cc0/

**Comment by greatislander** [comment] 2023-07-20 15:34
Updates:

### Creative Commons
"_Title_ Copyright ©2023 by Author Name is licensed under a Creative Commons Attribution License, except where otherwise noted."

### All Rights Reserved
"_Title_ Copyright ©2023 by Author Name. All Rights Reserved."

### Public Domain
"This work (_Title_ by Author Name) is free of known copyright restrictions."

### Creative Commons Zero
"To the extent possible under law, Author Name has waived all copyright and related or neighboring rights to _Title_, except where otherwise noted."

**Comment by SteelWagstaff** [comment] 2023-07-26 14:37
In testing, I notice that when there is no copyright year entered, the CC license statements display the number 0 just after the copyright logo. This doesn't happen with All Rights Reserved books.

![Screenshot from 2023-07-26 07-36-43](https://github.com/pressbooks/pressbooks/assets/13485451/e2413d93-417a-49a4-bf18-e8c3a2de3bbd)
![Screenshot from 2023-07-26 07-36-23](https://github.com/pressbooks/pressbooks/assets/13485451/16c2c812-8d2f-4208-b66f-5199a877252f)

**Comment by greatislander** [comment] 2023-07-26 14:40
Ah, thanks for catching that, @SteelWagstaff. Please reassign to me to address this.

**Comment by SteelWagstaff** [comment] 2023-07-31 16:05
Now works as expected for All Rights Reserved, all CC licenses, and Public Domain. There are two custom licenses used by eCampusOntario (Ontario Commons License & Ontario Commons License - No Derivatives). In these two cases, the copyright statement still needs to be adjusted, as it is output as follows: 

```
Test Book Copyright &copy; 2023
This book was produced with Pressbooks (https://pressbooks.com) and rendered with Prince.
```

This probably needs to be adjusted separately with a PR in the eCampusOntario plugin: https://github.com/pressbooks/pressbooks-ecampus-ontario/blob/1261d530cb242a973f6e8ecc923c902410c1d68d/inc/class-licenses.php#L91-L108

**Comment by SteelWagstaff** [comment] 2023-07-31 19:55
On further inspection, I think the issue here is that these licenses don't trigger any of the conditions in this block: https://github.com/pressbooks/pressbooks/blob/10178555219dc0124222d140ee977b8c7932fda2/inc/class-licensing.php#L430-L479

I'll work on a PR later today.

**Comment by tw77** [comment] 2023-08-03 18:14
@SteelWagstaff this is working as expected with other licenses, but I'm running into an issue testing with the Ontario Commons Licenses. 

On https://dev.pressbooks.network/, when I select either of the Ontario Commons Licenses, regardless of whether copyright year is specified, the license doesn't appear in the webbook metadata:
<img width="984" alt="Screenshot 2023-08-03 at 11 01 59 AM" src="https://github.com/pressbooks/pressbooks/assets/44182629/f9285457-f293-4310-b3e6-41bd58ec95d4">

and in PDF and EPUB exports, the license is always shown as the book title + `Copyright &copy; 2023`
<img width="331" alt="Screenshot 2023-08-03 at 11 14 01 AM" src="https://github.com/pressbooks/pressbooks/assets/44182629/404ba962-6cda-40d4-8742-c3d17d19a8fa">

**Comment by SteelWagstaff** [comment] 2023-08-03 18:36
Thanks for flagging this. The missing license in the webbook also happens on production networks, so we should file this as an existing bug rather than a new regression. Re: the copyright symbol, we should try to figure out what's up with the character entity for the copyright symbol not being properly decoded in the export html for these exports in particular.

**Comment by SteelWagstaff** [comment] 2023-08-03 19:05
Just checked -- the copyright symbol decoding issue is also present on production networks and is an existing bug rather than a new regression :sob: We can file these both as new bugs.

**Closed as completed** 2023-08-03 19:05 UTC
Labels: bug, External Consultant, minor
