### ISSUE TITLE
Modify TinyMCE Table button 

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#299] opened 2015-11-02 15:01 UTC
TABLE BUTTON SPEC:
- “Insert Table” (size interface)

- “Table Properties” Modal
	- General Options
		- Caption (checkbox)
		- Alignment dropdown (none, left, right, center)
		- Table type dropdown (no lines, lines, shaded, custom=field)

- “Table Cell Properties” Modal 
	- General Options 
		- Width
		- Cell Type
		- H Align
		- Scope 
		- V align
		- Border (checkmark or dropdown)
		- Shaded (checkmark or dropdown)
	

- “Table Row Properties” Modal 
	- General 
		- Row Type
		- Alignment
		- Border (checkmark or dropdown)
		- Shaded (checkmark or dropdown)

**Comment by greatislander** [comment] 2015-11-02 16:13
Duplicate of #291.

**Closed by greatislander** 2015-11-02 16:13 UTC
Labels: enhancement, priority
