### ISSUE TITLE
Feature request: It should be possible to set parts to be private

### ISSUE THREAD

**Issue by marcusschiesser** [pressbooks/pressbooks#209] opened 2015-08-13 11:14 UTC
Right now it is only possible to set chapters to be private, For parts this is not possible for the time being.

If  a part is set to be private, all its chapters should be private too.

**Comment by greatislander** [comment] 2015-08-13 12:23
@marcusschiesser I believe this is a duplicate of your issue #177.

**Closed** 2015-08-13 12:23 UTC
Labels: duplicate

**Comment by marcusschiesser** [comment] 2015-08-13 13:18
Yes you're right!
