### ISSUE TITLE
Can't save book info on dev.pressbooks.network

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#3719] opened 2024-06-06 16:03 UTC
When I attempt to update and save book info on the dev.pressbooks.network, the process fails and I see a 500 error:
![Screenshot from 2024-06-06 08-52-34](https://github.com/pressbooks/pressbooks/assets/13485451/7dbd4f96-31d7-448d-88ba-4e6cd3a1c2e7)

To reproduce:
1. open the book info page for a book on dev.pressbooks.pub
2. make a change and attempt to save book info
3. observe the 'This page isn't working' message

What should happen:
1. The book info should be updated for the book in question without failing

**Comment by cmurtagh** [comment] 2024-06-06 17:23
It looks like we're having problems with the latest version of ObjectCache Pro. I will chat with their support about this (which really means Till) and see what we will need to do to address it. Until then, we'll roll back to the previous version.

**Comment by arzola** [comment] 2024-06-06 17:28
This was caused by having both results for lms plugins active, I deactivated the new results for LMS on this network because the new one requires the new LTI plugin, now it should be working as expected

**Comment by arzola** [comment] 2024-06-25 17:09
I think we can close this one? @SteelWagstaff @cmurtagh ?

**Comment by SteelWagstaff** [comment] 2024-06-25 17:11
@arzola book information can now be saved on this network. I support closing this ticket now.

**Closed as completed** 2024-06-25 17:13 UTC
Labels: bug
