### ISSUE TITLE
The img tag in the license-attribution is not self-closing

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#1395] opened 2018-10-08 12:24 UTC
### Prerequisites

* [ ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
The img tag in the license-attribution is not self-closing. All other image tags in the exported xhtml file are self-closing `<img />` . In the license-attribution it is just `<img>`. This makes the xhtml file "invalid".

Example:

`<div class="license-attribution"><p><img src="http://pressbooks.delivros.ch/kvmanual/wp-content/themes/pressbooks-book/assets/book/images/cc-by.svg" alt="Icon for the Creative Commons Attribution 4.0 International License"></p><p>xxxx<span property="cc:attributionName">xxx</span> is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>, except where otherwise noted.</p></div>
`
#### Book Info

Book ID: 8
Book URL: http://pressbooks.delivros.ch/kvmanual/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 62.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 Firefox/62.0

#### WordPress Configuration

Network URL: http://pressbooks.delivros.ch/
Network Type: Subdirectory
Version: 4.9.8
Language: en_US
WP_ENV: development
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.5.2
Book Theme: pressbooks-kssg
Book Theme Version: 1.0
Root Theme: Aldine
Root Theme Version: 1.5.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Enable Media Replace: 3.2.7
H5P: 1.10.3
Hypothesis: 0.5.0
Pressbooks: 5.5.2
Pressbooks LTI Provider: 1.1.1
Re-send Welcome Email: 0.4.2
WP Mail SMTP: 1.3.3
WP QuickLaTeX: 3.8.5

#### Book Active Plugins

Enable Media Replace: 3.2.7
H5P: 1.10.3
Hypothesis: 0.5.0
Pressbooks: 5.5.2
Pressbooks LTI Provider: 1.1.1
Re-send Welcome Email: 0.4.2
WP Mail SMTP: 1.3.3
WP QuickLaTeX: 3.8.5

#### Server Configuration

PHP Version: 7.2.9-1+ubuntu16.04.1+deb.sury.org+1
MySQL Version: 5.7.23
Webserver Info: Apache/2.4.18 (Ubuntu)

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 128M
Post Max Size: 128M
Upload Max Filesize: 128M
Time Limit: 90
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.47.0
imagick: Not Installed
xsl: Installed

**Comment by connerbw** [comment] 2018-10-09 14:11
Long shot, but possibly related? https://github.com/Masterminds/html5-php/pull/137

**Comment by connerbw** [comment] 2018-10-09 14:21
On second thought, [all ](https://github.com/pressbooks/pressbooks/blob/233c4bd1d9c7e7b958e30da4b9c1422bddeec78b/inc/class-licensing.php#L390) [the img](https://github.com/pressbooks/pressbooks/blob/233c4bd1d9c7e7b958e30da4b9c1422bddeec78b/inc/class-licensing.php#L411) [tags ](https://github.com/pressbooks/pressbooks/blob/233c4bd1d9c7e7b958e30da4b9c1422bddeec78b/inc/class-licensing.php#L421) are all self closing, and they are not transformed by any parsers.

Is this because you are using Chrome inspector to view the source? 

![image](https://user-images.githubusercontent.com/812192/46675655-e44f0f00-cbac-11e8-959e-cf31fe1de7f1.png)

Versus actual source:

![image](https://user-images.githubusercontent.com/812192/46675693-fb8dfc80-cbac-11e8-8c0d-96917e3cc561.png)

Notice that in the second screenshot the img tag is closed.

**Comment by connerbw** [comment] 2018-10-09 14:32
Can you share the file? I cannot reproduce.

**Comment by greatislander** [comment] 2018-10-09 16:06
@thomasdumm You exported and then downloaded the export file?

**Comment by thomasdumm** [comment] 2018-10-09 16:07
yes

**Closed** 2018-10-09 17:12 UTC
Labels: bug
