### ISSUE TITLE
Unable to import .html file

### ISSUE THREAD

**Issue by josieg** [pressbooks/pressbooks#1148] opened 2018-03-14 19:04 UTC
### Description 

On the import page in Pressbooks, the "Web page/Pressbooks webbook (.html or URL)" import option allows users to either upload a file or import from a URL. The URL import works as expected, but trying to import an .html file does not work. 

**Expected behaviour** 

With the "Web page/Pressbooks webbook (.html or URL)" import option, there is an option to upload a file or import via a link. With both of those options present, I assume that I am able to import an .html file. 

If the "Web page/Pressbooks webbook (.html or URL)" import option is not designed to import an .html file, the option to upload a file should be removed for this import option. 

**Actual behaviour** 

1. I select the "Web page/Pressbooks webbook (.html or URL)" import option in Pressbooks.
2. I upload an .html file from a book in Pressbooks. 
3. I import the file. It is successful.
4. I go to the "Organize" page to view the imported content. It looks like the entire book has been added to one chapter. And when I click on the chapter, there is no content.

#### Root Blog Info

Root Blog ID: 1
Root Blog URL: https://pressbooksdev.bccampus.ca/

#### Browser

Platform: Windows
Browser Name: Chrome
Browser Version: 65.0.3325.146
User Agent String: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36

#### WordPress Configuration

Network URL: http://pressbooksdev.bccampus.ca/
Network Type: Subdirectory
Version: 4.9.4
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.0.2
Root Theme: Pressbooks Publisher
Root Theme Version: 3.1.4

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

BC Post-Secondary Validator: 1.0.0
Candela Thin Exports: 0.1
CC Export for Pressbooks: 0.2.1
f5 Force SSL: 1.0.0
iThemes Security: 6.9.2
mPDF for Pressbooks: 3.1.1
Openstax Import for Pressbooks: 1.0.0
Pressbooks: 5.0.2
Pressbooks Stats: 1.4.0
Textbooks for Pressbooks: 4.0.1
WP-Piwik: 1.0.19

#### Inactive Plugins

Akismet Anti-Spam: 4.0.3
BuddyPress: 2.9.3
H5P: 1.10.1
LTI: 0.1
WP QuickLaTeX: 3.8.4

#### Server Configuration

PHP Version: 7.1.14
MySQL Version: 5.5.5
Webserver Info: Apache

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 100M
Post Max Size: 100M
Upload Max Filesize: 100M
Time Limit: 60
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.19.7
imagick: Not Installed
xsl: Installed

**Comment by greatislander** [comment] 2018-03-14 19:06
Hi @josieg, thanks for the detailed report. Can you attach the HTML file you tried to import to this ticket so we can take a look at it? Thanks in advance.

**Comment by josieg** [comment] 2018-03-14 19:16
Hi Ned. It won't let me attach the html file here. 

But you can download it from this page: [Intro to Sociology](https://open.bccampus.ca/find-open-textbooks/?uuid=6140c265-61a6-455b-80b8-6ec8fcdf5a48&contributor=&keyword=&subject=). 

It's the one titled "Editable: .html file"

**Comment by connerbw** [comment] 2018-03-14 20:37
Because that's a creative commons book hosted on a recent version of Pressbooks, you can import (and clone) by pasting in the URL:

https://opentextbc.ca/introductiontosociology2ndedition/

I'll check the buggy behaviour with the HMTL file soon but if you need to do this now then use that workaround?

Thanks.

**Comment by connerbw** [comment] 2018-03-15 19:48
>  It looks like the entire book has been added to one chapter.

The HTML file being brought in as one chapter is expected behaviour. 

Even if Web page (HTML) and Pressbooks webbook (URL) both use the same select box option, Web page is not as sophisticated as Pressbooks webbook.

HTML import was originally conceived as a simple web scrapper. The prefered method to import an OER Pressbooks book is with the URL to the webbook.

> When I click on the chapter, there is no content.

[This is fixed now.](https://github.com/pressbooks/pressbooks/pull/1153)

Caveat: When I tested with your example Pressbooks downloaded 392 images. Took a long time...

**Closed** 2018-03-15 21:00 UTC
Labels: bug
