### ISSUE TITLE
mPDF options > two-level TOC

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#231] opened 2015-08-28 15:50 UTC
Current PDF export does not display 2 level TOC.

The Global Options - Enable a two-level TOC - applicable to mPDF TOC ?

Status:
Open Textbooks Theme Options enabled:
     - Display table of contents
     - Enable a two-level TOC

PressBooks Textbook Version 1.2.15
Pressbooks Version 2.6.5
Theme - Open Textbooks

**Comment by greatislander** [comment] 2015-08-28 16:02
This is a duplicate of https://github.com/pressbooks/pressbooks/issues/181. Multi-level TOC is not yet supported on mPDF but will eventually be once mPDF exports are based on XHTML.

**Closed** 2015-08-28 16:02 UTC
Labels: duplicate

**Comment by sswettenham** [comment] 2015-08-28 16:30
Fantastic news,
Thanks,

**Comment by jflowers45** [comment] 2015-08-28 16:57
@sswettenham I didn't make this a UI option but I did enable it on our version of mPDF exports.  it's not very elegant code - I sorta just needed to get it out the door for a particular PDF - and if you take it you may want to put the page numbers back in the formatted $toc_entry part.  But just in case you're interested

https://github.com/BBGInnovate/oddibooks/commit/66336134a082ca7ddd0678635d0988dfae68ce92

**Comment by jflowers45** [comment] 2015-08-28 17:05
@sswettenham Also we don't call HTMLawed in our version (we've had issues with it messing with Chinese characters), and we have two lines of code related to embedding different fonts based on selected language.  So if you check it out, beware you may want to copy things bit by bit rather than take the whole file.  But just wanted to make you aware of it in case you're desperate!

**Comment by sswettenham** [comment] 2015-08-28 20:43
Thanks that helps me understand mPDF a bit more, along with an interesting class-pb-pdf.php modification.
