### ISSUE TITLE
Make a Textbox TinyMCE button

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#300] opened 2015-11-02 15:03 UTC
- “Insert Textbox”
- “Textbox Properties” Modal: 
	- Textbox type dropdown (regular, shaded, learning objective, key takeaway, exercises, examples, custom=field)

**Comment by greatislander** [comment] 2015-11-02 16:15
Duplicate of #292.

**Closed by greatislander** 2015-11-02 16:15 UTC
Labels: duplicate
