### ISSUE TITLE
Large print PDF export timing out 

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1886] opened 2020-01-13 18:50 UTC
### Description

This seems to be a recurrence of a past bug that caused any export which took more than 10 minutes to time out before the file could be successfully created. We extended the timeout to 25 minutes (https://github.com/pressbooks/trellis-terraform-example/pull/105) because some particularly large books, especially from OpenStax, would be too big to export or clone. 

Timeouts are consistently happening at around the 10 minute mark again, and the resulting validation error reads: 
 >"status": "failed",  "validation_errors": "Timeout trying to create pdf from document content."

This only seems to be affecting the PDF exports at this time, but that may be related to file size. 

Example: https://chemistrytimeout.textopress.com/

### Steps to Reproduce

1. Visit a very large book
2. Export a digital or print PDF
3. See if the file successfully exports 

**Expected behavior:** All file types for any reasonably sized book can successfully export 

**Actual behavior:** PDFs cannot successfully export from a 270,000-word textbook

**Comment by SteelWagstaff** [comment] 2020-01-17 17:58
One book having this issue is https://press.rebus.community/introductorychemistry. 

One possible complication -- this book makes heavy use of LaTeX and uses the WP QuickLaTeX plugin. 

Other things to investigate -- we use the Docraptor service to generate PDFs with the PrinceXML tool. Their API includes and http timeout setting with default value of 10 (seconds): https://docraptor.com/documentation/api#api_http_timeout.

**Comment by SteelWagstaff** [comment] 2020-01-17 20:36
While size may be part of the problem (a successful EPUB3 export took over 11 minutes for me on a local installation) I don't think word count is the constraining factor here -- I can see half a dozen books over 300,000 words that have recently produced successful PDF exports on other production networks (like UCFs).

**Comment by SteelWagstaff** [comment] 2020-01-17 23:05
When running both digital and print PDF exports for the book locally (with WP Quick LaTeX turned off), the browser experienced an EventStream Connection Error at the 3 minute mark. 
![Screenshot from 2020-01-17 17-03-19](https://user-images.githubusercontent.com/13485451/72652186-50d9c180-394b-11ea-8390-abcacd71a2bd.png)
![Screenshot from 2020-01-17 17-03-31](https://user-images.githubusercontent.com/13485451/72652196-5505df00-394b-11ea-9a8f-a7456e5acdde.png)
The digital PDF export eventually completed successfully, but the print PDF export never did.

**Comment by SteelWagstaff** [comment] 2020-01-17 23:24
The resulting print PDF is over 7000 pages(!) and has several chapters that run hundreds of pages long -- with text pushed into tiny sidebars within sidebars -- here's one particularly concrete poetry-esque page: 
![Screenshot from 2020-01-17 17-23-41](https://user-images.githubusercontent.com/13485451/72652872-2c331900-394e-11ea-99cd-ba5db7c52a80.png)
In short, I think the problem here is with the underlying HTML rather than the export routine.

**Comment by SteelWagstaff** [comment] 2020-01-17 23:48
Found a bunch of div tags that never close, including several that are alignleft/alignright images. I think this is a big part of the problem for the book in question.

**Comment by SteelWagstaff** [comment] 2020-01-22 20:25
Closing as this appears to be an issue with the underlying HTML, not a bug with our export routine.

**Closed by SteelWagstaff** 2020-01-22 20:25 UTC
Labels: bug, export formats, wontfix
